### PR TITLE
zephyr: Enable MESH DFU and MBT

### PR DESCRIPTION
**Pull request by sjanc**
This allows to run those without MMDL.

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr MBT/SR/BT/BI-01-C DFU/SR/FD/BV-03-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1160#issuecomment-2097963407 after 12:19:28.

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Build and flash step failed

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1160#issuecomment-2097963407 after 12:36:54.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1160#issuecomment-2097963407 after 12:51:31.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>DFU     DFU/SR/FD/BV-03-C               PASS<br>MBT     MBT/SR/BT/BI-01-C               PASS</details>

**Review by m-alperen-sener — APPROVED** [review]

**Review by mkasenberg — APPROVED** [review]

**Pull request merged**
