### PR TITLE
Fix GAP/SEC/AUT/BV-19-C

### PR DESCRIPTION
**Pull request by piotrnarajowski**
- Fix GAP/SEC/AUT/BV-19-C:  WID108 appears twice in a row for this test with different descritpions. The point is to call gap_pair command only once.
- Add test case to mynewt errata list

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP/SEC/AUT/BV-19-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1223#issuecomment-2277859348, board: nrf52, estimated start time: 14:44:20, test case count: 1, estimated duration: 0:00:54<details><summary>Test cases to be run</summary>GAP/SEC/AUT/BV-19-C</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run zephyr GAP/SEC/AUT/BV-19-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1223#issuecomment-2277865988, board: nrf52, estimated start time: 14:46:51, test case count: 1, estimated duration: 0:00:17<details><summary>Test cases to be run</summary>GAP/SEC/AUT/BV-19-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GAP     GAP/SEC/AUT/BV-19-C             INCONC</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/SEC/AUT/BV-19-C             PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP --test_case_limit 10

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/SEC/AUT/BV-19-C             PASS</details>

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1223#issuecomment-2277966635, board: nrf52, estimated start time: 16:06:59, test case count: 10, estimated duration: 0:05:16<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C<br>GAP/BROB/BCST/BV-04-C<br>GAP/BROB/OBSV/BV-01-C<br>GAP/BROB/OBSV/BV-02-C<br>GAP/BROB/OBSV/BV-05-C<br>GAP/BROB/OBSV/BV-06-C<br>GAP/DISC/NONM/BV-01-C<br>GAP/DISC/NONM/BV-02-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GAP     GAP/BROB/BCST/BV-04-C           FAIL</details>
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS<br>GAP     GAP/BROB/BCST/BV-02-C           PASS<br>GAP     GAP/BROB/BCST/BV-03-C           PASS<br>GAP     GAP/BROB/OBSV/BV-01-C           PASS<br>GAP     GAP/BROB/OBSV/BV-02-C           PASS<br>GAP     GAP/BROB/OBSV/BV-05-C           PASS<br>GAP     GAP/BROB/OBSV/BV-06-C           PASS<br>GAP     GAP/DISC/NONM/BV-01-C           PASS<br>GAP     GAP/DISC/NONM/BV-02-C           PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP/SEC/AUT/BV-19-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1223#issuecomment-2293001714, board: nrf52, estimated start time: 09:47:06, test case count: 1, estimated duration: 0:00:52<details><summary>Test cases to be run</summary>GAP/SEC/AUT/BV-19-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/SEC/AUT/BV-19-C             PASS</details>

**Comment by piotrnarajowski** [comment]
@sjanc please review

**Comment by sjanc** [comment]
#AutoPTS run zephyr GAP/SEC/AUT/BV-19-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1223#issuecomment-2317144413, board: nrf52, estimated start time: 11:31:44, test case count: 1, estimated duration: 0:00:17<details><summary>Test cases to be run</summary>GAP/SEC/AUT/BV-19-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/SEC/AUT/BV-19-C             PASS</details>

**Review by sjanc — APPROVED** [review]

**Pull request merged**
