### PR TITLE
bot: Add a test run backup mode

### PR DESCRIPTION
**Pull request by mkasenberg**
If the 'use_backup' option is set to True in a config.py, the bot collects a backup of the stats, so in case of unexpected termination the bot can continue the test series from the test case where it was interrupted.

### CODE REVIEW

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr AICS

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1189#issuecomment-2208842932, board: nrf53, estimated start time: 14:23:44, test case count: 19, estimated duration: 0:07:32<details><summary>Test cases to be run</summary>AICS/SR/SGGIT/SER/BV-01-C<br>AICS/SR/SGGIT/CHA/BV-01-C<br>AICS/SR/SGGIT/CHA/BV-02-C<br>AICS/SR/SGGIT/CHA/BV-03-C<br>AICS/SR/SGGIT/CHA/BV-04-C<br>AICS/SR/SGGIT/CHA/BV-05-C<br>AICS/SR/SGGIT/CHA/BV-06-C<br>AICS/SR/SGGIT/CP/BI-01-C<br>AICS/SR/SGGIT/CP/BI-02-C<br>AICS/SR/SGGIT/CP/BI-03-C<br>AICS/SR/SGGIT/CP/BI-04-C<br>AICS/SR/SPN/BV-01-C<br>AICS/SR/SPN/BV-02-C<br>AICS/SR/CP/BV-01-C<br>AICS/SR/CP/BV-02-C<br>AICS/SR/CP/BV-03-C<br>AICS/SR/CP/BV-04-C<br>AICS/SR/CP/BV-05-C<br>AICS/SR/SPE/BI-01-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>AICS    AICS/SR/CP/BV-01-C              PASS<br>AICS    AICS/SR/CP/BV-02-C              PASS<br>AICS    AICS/SR/CP/BV-03-C              PASS<br>AICS    AICS/SR/CP/BV-04-C              PASS<br>AICS    AICS/SR/CP/BV-05-C              PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-01-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-02-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-03-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-04-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-05-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-06-C       PASS<br>AICS    AICS/SR/SGGIT/CP/BI-01-C        PASS<br>AICS    AICS/SR/SGGIT/CP/BI-02-C        PASS<br>AICS    AICS/SR/SGGIT/CP/BI-03-C        PASS<br>AICS    AICS/SR/SGGIT/CP/BI-04-C        PASS<br>AICS    AICS/SR/SGGIT/SER/BV-01-C       PASS<br>AICS    AICS/SR/SPE/BI-01-C             PASS<br>AICS    AICS/SR/SPN/BV-01-C             PASS<br>AICS    AICS/SR/SPN/BV-02-C             PASS</details>

**Review by sjanc — APPROVED** [review]

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1189#issuecomment-2213469928, board: nrf53, estimated start time: 11:12:16, test case count: 19, estimated duration: 0:07:32<details><summary>Test cases to be run</summary>AICS/SR/SGGIT/SER/BV-01-C<br>AICS/SR/SGGIT/CHA/BV-01-C<br>AICS/SR/SGGIT/CHA/BV-02-C<br>AICS/SR/SGGIT/CHA/BV-03-C<br>AICS/SR/SGGIT/CHA/BV-04-C<br>AICS/SR/SGGIT/CHA/BV-05-C<br>AICS/SR/SGGIT/CHA/BV-06-C<br>AICS/SR/SGGIT/CP/BI-01-C<br>AICS/SR/SGGIT/CP/BI-02-C<br>AICS/SR/SGGIT/CP/BI-03-C<br>AICS/SR/SGGIT/CP/BI-04-C<br>AICS/SR/SPN/BV-01-C<br>AICS/SR/SPN/BV-02-C<br>AICS/SR/CP/BV-01-C<br>AICS/SR/CP/BV-02-C<br>AICS/SR/CP/BV-03-C<br>AICS/SR/CP/BV-04-C<br>AICS/SR/CP/BV-05-C<br>AICS/SR/SPE/BI-01-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>AICS    AICS/SR/CP/BV-01-C              PASS<br>AICS    AICS/SR/CP/BV-02-C              PASS<br>AICS    AICS/SR/CP/BV-03-C              PASS<br>AICS    AICS/SR/CP/BV-04-C              PASS<br>AICS    AICS/SR/CP/BV-05-C              PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-01-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-02-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-03-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-04-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-05-C       PASS<br>AICS    AICS/SR/SGGIT/CHA/BV-06-C       PASS<br>AICS    AICS/SR/SGGIT/CP/BI-01-C        PASS<br>AICS    AICS/SR/SGGIT/CP/BI-02-C        PASS<br>AICS    AICS/SR/SGGIT/CP/BI-03-C        PASS<br>AICS    AICS/SR/SGGIT/CP/BI-04-C        PASS<br>AICS    AICS/SR/SGGIT/SER/BV-01-C       PASS<br>AICS    AICS/SR/SPE/BI-01-C             PASS<br>AICS    AICS/SR/SPN/BV-01-C             PASS<br>AICS    AICS/SR/SPN/BV-02-C             PASS</details>

**Pull request merged**
