### PR TITLE
zephyr: csis: add BTP command

### PR DESCRIPTION
**Pull request by piotrnarajowski**
- Add BTP command to change SIRK type to encrypted. Fixes CSIS/SR/SP/BV-08-C
 - Fix TSPX_time_guard typo
Merge after https://github.com/zephyrproject-rtos/zephyr/pull/70783

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
@KKopyscinski please review

**Comment by KKopyscinski** [comment]
LGTM, but add command description ind doc/btp_csis.txt

**Comment by piotrnarajowski** [comment]
@KKopyscinski  added command description

**Review by KKopyscinski — APPROVED** [review]
LGTM

**Comment by piotrnarajowski** [comment]
@KKopyscinski made few changes, please review again

**Review by KKopyscinski — APPROVED** [review]
LGTM, I like that this sets value instead of just enabling

**Review by sjanc — APPROVED** [review]

**Pull request merged**
