### PR TITLE
Mynewt: fix writing EATT supported bit

### PR DESCRIPTION
**Pull request by KKopyscinski**
Mynewt now writes EATT supported wid on encryption changed, not connection event.

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run mynewt GATT/CL

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GATT    GATT/CL/GAD/BV-03-C             INCONC<br>GATT    GATT/CL/GAN/BV-02-C             FAIL<br>GATT    GATT/CL/GAR/BI-36-C             INCONC<br>GATT    GATT/CL/GAR/BI-38-C             INCONC<br>GATT    GATT/CL/GAR/BI-42-C             INCONC<br>GATT    GATT/CL/GAR/BI-44-C             INCONC<br>GATT    GATT/CL/GAR/BV-10-C             INCONC</details>
<details><summary>Successful tests</summary>GATT    GATT/CL/GAC/BV-01-C             PASS<br>GATT    GATT/CL/GAD/BV-01-C             PASS<br>GATT    GATT/CL/GAD/BV-02-C             PASS<br>GATT    GATT/CL/GAD/BV-04-C             PASS<br>GATT    GATT/CL/GAD/BV-05-C             PASS<br>GATT    GATT/CL/GAD/BV-06-C             PASS<br>GATT    GATT/CL/GAI/BI-01-C             PASS<br>GATT    GATT/CL/GAI/BV-01-C             PASS<br>GATT    GATT/CL/GAN/BV-01-C             PASS<br>GATT    GATT/CL/GAR/BI-01-C             PASS<br>GATT    GATT/CL/GAR/BI-02-C             PASS<br>GATT    GATT/CL/GAR/BI-04-C             PASS<br>GATT    GATT/CL/GAR/BI-05-C             PASS<br>GATT    GATT/CL/GAR/BI-06-C             PASS<br>GATT    GATT/CL/GAR/BI-07-C             PASS<br>GATT    GATT/CL/GAR/BI-10-C             PASS<br>GATT    GATT/CL/GAR/BI-11-C             PASS<br>GATT    GATT/CL/GAR/BI-12-C             PASS<br>GATT    GATT/CL/GAR/BI-13-C             PASS<br>GATT    GATT/CL/GAR/BI-14-C             PASS<br>GATT    GATT/CL/GAR/BI-16-C             PASS<br>GATT    GATT/CL/GAR/BI-17-C             PASS<br>GATT    GATT/CL/GAR/BI-18-C             PASS<br>GATT    GATT/CL/GAR/BI-19-C             PASS<br>GATT    GATT/CL/GAR/BI-21-C             PASS<br>GATT    GATT/CL/GAR/BI-22-C             PASS<br>GATT    GATT/CL/GAR/BI-35-C             PASS<br>GATT    GATT/CL/GAR/BV-01-C             PASS<br>GATT    GATT/CL/GAR/BV-03-C             PASS<br>GATT    GATT/CL/GAR/BV-04-C             PASS (2)<br>GATT    GATT/CL/GAR/BV-05-C             PASS<br>GATT    GATT/CL/GAR/BV-06-C             PASS<br>GATT    GATT/CL/GAR/BV-07-C             PASS<br>GATT    GATT/CL/GAR/BV-08-C             PASS<br>GATT    GATT/CL/GAS/BV-01-C             PASS<br>GATT    GATT/CL/GAT/BV-01-C             PASS<br>GATT    GATT/CL/GAT/BV-02-C             PASS<br>GATT    GATT/CL/GAT/BV-03-C             PASS<br>GATT    GATT/CL/GAW/BI-02-C             PASS<br>GATT    GATT/CL/GAW/BI-03-C             PASS<br>GATT    GATT/CL/GAW/BI-05-C             PASS<br>GATT    GATT/CL/GAW/BI-06-C             PASS<br>GATT    GATT/CL/GAW/BI-07-C             PASS<br>GATT    GATT/CL/GAW/BI-08-C             PASS<br>GATT    GATT/CL/GAW/BI-09-C             PASS<br>GATT    GATT/CL/GAW/BI-12-C             PASS<br>GATT    GATT/CL/GAW/BI-13-C             PASS<br>GATT    GATT/CL/GAW/BI-32-C             PASS<br>GATT    GATT/CL/GAW/BI-33-C             PASS<br>GATT    GATT/CL/GAW/BI-34-C             PASS<br>GATT    GATT/CL/GAW/BV-01-C             PASS<br>GATT    GATT/CL/GAW/BV-03-C             PASS<br>GATT    GATT/CL/GAW/BV-05-C             PASS<br>GATT    GATT/CL/GAW/BV-06-C             PASS<br>GATT    GATT/CL/GAW/BV-08-C             PASS<br>GATT    GATT/CL/GAW/BV-09-C             PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run mynewt  GATT/CL/GAR/BV-10-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1134#issuecomment-2012377943 after 15:02:42.

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Build and flash step failed

**Comment by sjanc** [comment]
#AutoPTS run mynewt GATT/CL/GAR/BV-10-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1134#issuecomment-2017481338 after 09:45:09.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GATT    GATT/CL/GAR/BV-10-C             PASS</details>

**Review by sjanc — APPROVED** [review]

**Pull request merged**
