### PR TITLE
cron: Extend 'PR scheduled' comment to add estimations

### PR DESCRIPTION
**Pull request by mkasenberg**
Extend the cron comment with info about estimated time duration and number of test cases to be run.
Plus other small, cron related fixes/changes.

### CODE REVIEW

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr AICS -e AICS/SR/SGGIT AICS/SR/SPN

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/auto-pts/auto-pts/pull/1149#issuecomment-2047037134, estimated start time: 11:39:42, test case count: 6, estimated duration: 0:03:12

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>AICS    AICS/SR/CP/BV-01-C              PASS<br>AICS    AICS/SR/CP/BV-02-C              PASS<br>AICS    AICS/SR/CP/BV-03-C              PASS<br>AICS    AICS/SR/CP/BV-04-C              PASS<br>AICS    AICS/SR/CP/BV-05-C              PASS<br>AICS    AICS/SR/SPE/BI-01-C             PASS</details>

**Review by sjanc — APPROVED** [review]

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr nrf52 DIS

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/auto-pts/auto-pts/pull/1149#issuecomment-2119864977, estimated start time: 09:44:39, test case count: 8, estimated duration: 0:02:35<details><summary>Test cases to be run</summary>DIS/SR/SGGIT/SER/BV-01-C<br>DIS/SR/SGGIT/CHA/BV-01-C<br>DIS/SR/SGGIT/CHA/BV-02-C<br>DIS/SR/SGGIT/CHA/BV-03-C<br>DIS/SR/SGGIT/CHA/BV-04-C<br>DIS/SR/SGGIT/CHA/BV-05-C<br>DIS/SR/SGGIT/CHA/BV-06-C<br>DIS/SR/SGGIT/CHA/BV-09-C</details>

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1149#issuecomment-2119864977 after 09:46:04.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>DIS     DIS/SR/SGGIT/CHA/BV-01-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-02-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-03-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-04-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-05-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-06-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-09-C        PASS<br>DIS     DIS/SR/SGGIT/SER/BV-01-C        PASS</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>DIS     DIS/SR/SGGIT/CHA/BV-01-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-02-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-03-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-04-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-05-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-06-C        PASS<br>DIS     DIS/SR/SGGIT/CHA/BV-09-C        PASS<br>DIS     DIS/SR/SGGIT/SER/BV-01-C        PASS</details>

**Pull request merged**
