### PR TITLE
zephyr: Simplify GATT server tests configurations

### PR DESCRIPTION
**Pull request by sjanc**
Use common settings reducing number of custom test cases and WIDs. Update generic WIDs handlers to PTS 8.4 requirements and make them more generic.

depends on:
https://github.com/zephyrproject-rtos/zephyr/pull/56214

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr GATT/SR/GAS/BV-03-C GATT/SR/GAN/BV-02-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/893#issuecomment-1486447286 after 10:41:22.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
Failed tests:
GATT    GATT/SR/GAN/BV-02-C             BTP ERROR

**Comment by sjanc** [comment]
#AutoPTS run zephyr GATT/SR/GAS/BV-03-C GATT/SR/GAN/BV-02-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/893#issuecomment-1486809059 after 14:38:14.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.

**Review by mkasenberg — APPROVED** [review]

**Pull request merged**
