### PR TITLE
wids: Refactor generic wid to handle synch

### PR DESCRIPTION
**Pull request by mkasenberg**
Unifies duplicate code.

### CODE REVIEW

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr MESH

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/915#issuecomment-1551205973 after 13:21:29.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/915#issuecomment-1551205973 after 14:08:59.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>MESH    MESH/PVNR/MPS/BV-01-C           INCONC<br>MESH    MESH/PVNR/MPS/BV-02-C           INCONC<br>MESH    MESH/PVNR/MPS/BV-03-C           INCONC<br>MESH    MESH/PVNR/MPS/BV-04-C           INCONC<br>MESH    MESH/PVNR/MPS/BV-05-C           INCONC<br>MESH    MESH/PVNR/MPS/BV-06-C           INCONC<br>MESH    MESH/PVNR/MPS/BV-08-C           INCONC<br>MESH    MESH/PVNR/MPS/BV-09-C           INCONC</details>
<details><summary>Successful tests</summary>MESH    MESH/NODE/BCN/SNB/BV-01-C       PASS<br>MESH    MESH/NODE/IVU/BV-01-C           PASS<br>MESH    MESH/NODE/MPS/BI-01-C           PASS<br>MESH    MESH/NODE/MPS/BV-01-C           PASS<br>MESH    MESH/NODE/MPS/BV-02-C           PASS<br>MESH    MESH/NODE/MPS/BV-03-C           PASS<br>MESH    MESH/NODE/MPS/BV-04-C           PASS<br>MESH    MESH/NODE/MPS/BV-05-C           PASS<br>MESH    MESH/NODE/MPS/BV-06-C           PASS<br>MESH    MESH/NODE/MPS/BV-07-C           PASS<br>MESH    MESH/NODE/MPS/BV-08-C           PASS<br>MESH    MESH/NODE/MPS/BV-09-C           PASS<br>MESH    MESH/NODE/MPS/BV-10-C           PASS<br>MESH    MESH/NODE/NET/BI-01-C           PASS<br>MESH    MESH/NODE/NET/BI-02-C           PASS<br>MESH    MESH/NODE/NET/BI-03-C           PASS<br>MESH    MESH/NODE/NET/BV-01-C           PASS<br>MESH    MESH/NODE/NET/BV-02-C           PASS<br>MESH    MESH/NODE/NET/BV-03-C           PASS<br>MESH    MESH/NODE/NET/BV-04-C           PASS<br>MESH    MESH/NODE/NET/BV-05-C           PASS<br>MESH    MESH/NODE/NET/BV-06-C           PASS<br>MESH    MESH/NODE/NET/BV-07-C           PASS<br>MESH    MESH/NODE/NET/BV-08-C           PASS<br>MESH    MESH/NODE/NET/BV-09-C           PASS<br>MESH    MESH/NODE/NET/BV-10-C           PASS<br>MESH    MESH/NODE/NET/BV-11-C           PASS<br>MESH    MESH/NODE/NET/BV-12-C           PASS<br>MESH    MESH/NODE/NET/BV-13-C           PASS<br>MESH    MESH/NODE/NET/BV-14-C           PASS<br>MESH    MESH/NODE/PBADV/BI-01-C         PASS<br>MESH    MESH/NODE/PBADV/BI-02-C         PASS<br>MESH    MESH/NODE/PBADV/BI-03-C         PASS<br>MESH    MESH/NODE/PBADV/BI-04-C         PASS<br>MESH    MESH/NODE/PBADV/BV-01-C         PASS<br>MESH    MESH/NODE/PBADV/BV-02-C         PASS<br>MESH    MESH/NODE/PBADV/BV-03-C         PASS<br>MESH    MESH/NODE/PBADV/BV-04-C         PASS<br>MESH    MESH/NODE/PROV/BI-01-C          PASS<br>MESH    MESH/NODE/PROV/BI-02-C          PASS<br>MESH    MESH/NODE/PROV/BI-03-C          PASS<br>MESH    MESH/NODE/PROV/BI-13-C          PASS<br>MESH    MESH/NODE/PROV/BI-15-C          PASS<br>MESH    MESH/NODE/PROV/BI-17-C          PASS<br>MESH    MESH/NODE/PROV/BV-01-C          PASS<br>MESH    MESH/NODE/PROV/BV-02-C          PASS<br>MESH    MESH/NODE/PROV/BV-03-C          PASS<br>MESH    MESH/NODE/PROV/BV-04-C          PASS<br>MESH    MESH/NODE/PROV/BV-05-C          PASS<br>MESH    MESH/NODE/PROV/BV-06-C          PASS<br>MESH    MESH/NODE/PROV/BV-07-C          PASS<br>MESH    MESH/NODE/PROV/BV-08-C          PASS<br>MESH    MESH/NODE/PROV/BV-09-C          PASS<br>MESH    MESH/NODE/PROV/BV-10-C          PASS<br>MESH    MESH/NODE/PROV/BV-11-C          PASS<br>MESH    MESH/NODE/PROV/BV-12-C          PASS<br>MESH    MESH/NODE/RLY/BI-01-C           PASS<br>MESH    MESH/NODE/RLY/BI-02-C           PASS<br>MESH    MESH/NODE/RLY/BV-01-C           PASS<br>MESH    MESH/NODE/RLY/BV-02-C           PASS<br>MESH    MESH/NODE/TNPT/BI-01-C          PASS<br>MESH    MESH/NODE/TNPT/BI-02-C          PASS<br>MESH    MESH/NODE/TNPT/BV-01-C          PASS<br>MESH    MESH/NODE/TNPT/BV-02-C          PASS<br>MESH    MESH/NODE/TNPT/BV-03-C          PASS<br>MESH    MESH/NODE/TNPT/BV-04-C          PASS<br>MESH    MESH/NODE/TNPT/BV-05-C          PASS<br>MESH    MESH/NODE/TNPT/BV-06-C          PASS<br>MESH    MESH/NODE/TNPT/BV-07-C          PASS<br>MESH    MESH/NODE/TNPT/BV-08-C          PASS<br>MESH    MESH/NODE/TNPT/BV-09-C          PASS<br>MESH    MESH/NODE/TNPT/BV-10-C          PASS<br>MESH    MESH/NODE/TNPT/BV-11-C          PASS<br>MESH    MESH/NODE/TNPT/BV-12-C          PASS<br>MESH    MESH/NODE/TNPT/BV-13-C          PASS<br>MESH    MESH/PVNR/PBADV/BI-01-C         PASS<br>MESH    MESH/PVNR/PBADV/BV-01-C         PASS<br>MESH    MESH/PVNR/PBADV/BV-02-C         PASS<br>MESH    MESH/PVNR/PBADV/BV-03-C         PASS<br>MESH    MESH/PVNR/PROV/BI-14-C          PASS<br>MESH    MESH/PVNR/PROV/BI-16-C          PASS<br>MESH    MESH/PVNR/PROV/BI-18-C          PASS<br>MESH    MESH/PVNR/PROV/BV-01-C          PASS<br>MESH    MESH/PVNR/PROV/BV-02-C          PASS<br>MESH    MESH/PVNR/PROV/BV-03-C          PASS<br>MESH    MESH/PVNR/PROV/BV-04-C          PASS<br>MESH    MESH/PVNR/PROV/BV-05-C          PASS<br>MESH    MESH/PVNR/PROV/BV-06-C          PASS<br>MESH    MESH/PVNR/PROV/BV-07-C          PASS<br>MESH    MESH/PVNR/PROV/BV-08-C          PASS<br>MESH    MESH/PVNR/PROV/BV-09-C          PASS<br>MESH    MESH/PVNR/PROV/BV-10-C          PASS</details>

**Pull request merged**
