### PR TITLE
doc: add ASCS

### PR DESCRIPTION
**Pull request by mringwal**
This is the draft for BTP ASCS service and I'd like to some feedback on it. (Looks like I should have selected 'create draft pull request' and now cannot mark it as draft. I'll use that the next time). 

Our btp-iut implementation is based on it and it allows to pass the BAP Unicast Client & Server Configuration (SCC) and Streaming (STR) tests.

### CODE REVIEW

**Comment by sjanc** [comment]
so I'm not sure if we should put such detailed parameters for BTP commands,  are those required by tests?

**Comment by mringwal** [comment]
> so I'm not sure if we should put such detailed parameters for BTP commands, are those required by tests?

Which ones? But yes, I'm afraid the tests require that level of detail. E.g. the BAP Unicast Client Streaming Tests, BAP/UCL/STR/BV-xxx-C, the client needs to configure the server with a particular configuration. 

While I've added everything that looked like it would be needed, there's a chance that there might be a field or another which is not actually needed, but in general, all these are necessary.

**Comment by MariuszSkamra** [comment]
@mringwal FYI, there's PR open https://github.com/auto-pts/auto-pts/pull/866 that adds the support for ASCS and BAP

**Comment by mringwal** [comment]
As #866 has been merged and contains a ASCS service, this one has become obsolete. Closing.

**Pull request closed without merging**
