### PR TITLE
Zephyr: Update to PTS 8.6.1

### PR DESCRIPTION
**Pull request by sjanc**
This updates workspace to PTS 8.6.1 and adds fixes for proper execution of GTBS and GMCS.

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr GTBS GMCS

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1220#issuecomment-2276523592, board: nrf53, estimated start time: 21:39:59, test case count: 0, estimated duration: None

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1220#issuecomment-2276523592, board: nrf53, estimated start time: 11:31:38, test case count: estimation not available

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1220#issuecomment-2276523592, board: nrf53, estimated start time: 11:48:44, test case count: estimation not available

**Review by mkasenberg — APPROVED** [review]

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GMCS    GMCS/SR/MCP/BV-09-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/67312<br>GMCS    GMCS/SR/MCP/BV-14-C             FAIL<br>GMCS    GMCS/SR/MCP/BV-15-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-16-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-17-C             FAIL - ERRATA Request ID 31410<br>GMCS    GMCS/SR/MCP/BV-18-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-19-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-20-C             FAIL - ERRATA Request ID 31410<br>GMCS    GMCS/SR/MCP/BV-21-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-22-C             FATAL ERROR<br>GMCS    GMCS/SR/MCP/BV-23-C             FAIL<br>GMCS    GMCS/SR/MCP/BV-24-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-25-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-26-C             FAIL - ERRATA Request ID 31410<br>GMCS    GMCS/SR/MCP/BV-27-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-28-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-29-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-38-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-39-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-40-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-41-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-42-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-43-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-44-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-45-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-46-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-47-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-48-C             FATAL ERROR<br>GMCS    GMCS/SR/MCP/BV-49-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-50-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-51-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-52-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-53-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-54-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-55-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-56-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-57-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-58-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-59-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-60-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-61-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-62-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-63-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-64-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-65-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-66-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-67-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-68-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-69-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-80-C             INCONC<br>GMCS    GMCS/SR/SCP/BV-01-C             INCONC<br>GMCS    GMCS/SR/SPN/BV-01-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/65062<br>GMCS    GMCS/SR/SPN/BV-02-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/65062</details>
<details><summary>Successful tests</summary>GMCS    GMCS/SR/MCP/BV-01-C             PASS<br>GMCS    GMCS/SR/MCP/BV-02-C             PASS<br>GMCS    GMCS/SR/MCP/BV-03-C             PASS<br>GMCS    GMCS/SR/MCP/BV-04-C             PASS<br>GMCS    GMCS/SR/MCP/BV-05-C             PASS<br>GMCS    GMCS/SR/MCP/BV-06-C             PASS<br>GMCS    GMCS/SR/MCP/BV-07-C             PASS<br>GMCS    GMCS/SR/MCP/BV-08-C             PASS<br>GMCS    GMCS/SR/MCP/BV-10-C             PASS<br>GMCS    GMCS/SR/MCP/BV-11-C             PASS<br>GMCS    GMCS/SR/MCP/BV-12-C             PASS<br>GMCS    GMCS/SR/MCP/BV-13-C             PASS<br>GMCS    GMCS/SR/MCP/BV-30-C             PASS<br>GMCS    GMCS/SR/MCP/BV-31-C             PASS<br>GMCS    GMCS/SR/MCP/BV-32-C             PASS<br>GMCS    GMCS/SR/MCP/BV-33-C             PASS<br>GMCS    GMCS/SR/MCP/BV-34-C             PASS<br>GMCS    GMCS/SR/MCP/BV-35-C             PASS<br>GMCS    GMCS/SR/MCP/BV-36-C             PASS<br>GMCS    GMCS/SR/MCP/BV-37-C             PASS<br>GMCS    GMCS/SR/MCP/BV-70-C             PASS<br>GMCS    GMCS/SR/MCP/BV-71-C             PASS<br>GMCS    GMCS/SR/MCP/BV-72-C             PASS<br>GMCS    GMCS/SR/MCP/BV-73-C             PASS<br>GMCS    GMCS/SR/MCP/BV-74-C             PASS<br>GMCS    GMCS/SR/MCP/BV-75-C             PASS<br>GMCS    GMCS/SR/MCP/BV-76-C             PASS<br>GMCS    GMCS/SR/MCP/BV-77-C             PASS<br>GMCS    GMCS/SR/MCP/BV-78-C             PASS<br>GMCS    GMCS/SR/MCP/BV-79-C             PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-01-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-02-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-03-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-04-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-05-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-06-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-07-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-08-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-09-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-10-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-11-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-12-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-13-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-14-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-15-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-16-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-17-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-18-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-19-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-20-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-21-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-22-C       PASS<br>GMCS    GMCS/SR/SGGIT/SER/BV-01-C       PASS<br>GMCS    GMCS/SR/SP/BV-01-C              PASS<br>GMCS    GMCS/SR/SP/BV-02-C              PASS<br>GMCS    GMCS/SR/SP/BV-03-C              PASS<br>GMCS    GMCS/SR/SPE/BI-01-C             PASS<br>GMCS    GMCS/SR/SPE/BI-02-C             PASS<br>GMCS    GMCS/SR/SPE/BI-03-C             PASS<br>GMCS    GMCS/SR/SPE/BI-04-C             PASS<br>GMCS    GMCS/SR/SPE/BI-05-C             PASS<br>GMCS    GMCS/SR/SPE/BI-06-C             PASS<br>GMCS    GMCS/SR/SPE/BI-07-C             PASS<br>GTBS    GTBS/SR/CP/BV-01-C              PASS<br>GTBS    GTBS/SR/CP/BV-02-C              PASS<br>GTBS    GTBS/SR/CP/BV-08-C              PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-01-C       PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-02-C       PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-03-C       PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-04-C       PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-07-C       PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-08-C       PASS - ERRATA Request ID 31633<br>GTBS    GTBS/SR/SGGIT/CHA/BV-09-C       PASS - ERRATA Request ID 31633<br>GTBS    GTBS/SR/SGGIT/CHA/BV-11-C       PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-12-C       PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-13-C       PASS - ERRATA Request ID 31633<br>GTBS    GTBS/SR/SGGIT/CHA/BV-14-C       PASS<br>GTBS    GTBS/SR/SGGIT/CHA/BV-15-C       PASS<br>GTBS    GTBS/SR/SGGIT/SER/BV-01-C       PASS<br>GTBS    GTBS/SR/SP/BV-02-C              PASS<br>GTBS    GTBS/SR/SPE/BI-01-C             PASS<br>GTBS    GTBS/SR/SPE/BI-02-C             PASS<br>GTBS    GTBS/SR/SPE/BI-04-C             PASS<br>GTBS    GTBS/SR/SPN/BV-01-C             PASS<br>GTBS    GTBS/SR/SPN/BV-02-C             PASS<br>GTBS    GTBS/SR/SPN/BV-04-C             PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run zephyr GMCS

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1220#issuecomment-2278066588, board: nrf53, estimated start time: 16:24:34, test case count: estimation not available

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GMCS    GMCS/SR/MCP/BV-09-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/67312<br>GMCS    GMCS/SR/MCP/BV-15-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-18-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-21-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-24-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-27-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-37-C             FAIL<br>GMCS    GMCS/SR/MCP/BV-38-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-41-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-42-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-45-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-46-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-49-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-50-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-53-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-54-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-57-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-58-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-61-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-62-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-65-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-66-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-69-C             INCONC<br>GMCS    GMCS/SR/MCP/BV-80-C             INCONC<br>GMCS    GMCS/SR/SCP/BV-01-C             INCONC<br>GMCS    GMCS/SR/SPN/BV-01-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/65062<br>GMCS    GMCS/SR/SPN/BV-02-C             INCONC - ERRATA https://github.com/zephyrproject-rtos/zephyr/issues/65062</details>
<details><summary>Successful tests</summary>GMCS    GMCS/SR/MCP/BV-05-C             PASS<br>GMCS    GMCS/SR/MCP/BV-07-C             PASS<br>GMCS    GMCS/SR/MCP/BV-12-C             PASS<br>GMCS    GMCS/SR/MCP/BV-30-C             PASS<br>GMCS    GMCS/SR/MCP/BV-33-C             PASS<br>GMCS    GMCS/SR/MCP/BV-34-C             PASS<br>GMCS    GMCS/SR/MCP/BV-70-C             PASS<br>GMCS    GMCS/SR/MCP/BV-71-C             PASS<br>GMCS    GMCS/SR/MCP/BV-72-C             PASS<br>GMCS    GMCS/SR/MCP/BV-73-C             PASS<br>GMCS    GMCS/SR/MCP/BV-74-C             PASS<br>GMCS    GMCS/SR/MCP/BV-75-C             PASS<br>GMCS    GMCS/SR/MCP/BV-76-C             PASS<br>GMCS    GMCS/SR/MCP/BV-77-C             PASS<br>GMCS    GMCS/SR/MCP/BV-78-C             PASS<br>GMCS    GMCS/SR/MCP/BV-79-C             PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-01-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-02-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-03-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-04-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-05-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-06-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-07-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-08-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-09-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-10-C       PASS (2)<br>GMCS    GMCS/SR/SGGIT/CHA/BV-11-C       PASS (2)<br>GMCS    GMCS/SR/SGGIT/CHA/BV-12-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-13-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-14-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-15-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-16-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-17-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-18-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-19-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-20-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-21-C       PASS<br>GMCS    GMCS/SR/SGGIT/CHA/BV-22-C       PASS<br>GMCS    GMCS/SR/SGGIT/SER/BV-01-C       PASS<br>GMCS    GMCS/SR/SP/BV-01-C              PASS<br>GMCS    GMCS/SR/SP/BV-02-C              PASS<br>GMCS    GMCS/SR/SP/BV-03-C              PASS<br>GMCS    GMCS/SR/SPE/BI-01-C             PASS<br>GMCS    GMCS/SR/SPE/BI-02-C             PASS<br>GMCS    GMCS/SR/SPE/BI-03-C             PASS<br>GMCS    GMCS/SR/SPE/BI-04-C             PASS<br>GMCS    GMCS/SR/SPE/BI-05-C             PASS<br>GMCS    GMCS/SR/SPE/BI-06-C             PASS<br>GMCS    GMCS/SR/SPE/BI-07-C             PASS</details>

**Pull request merged**
