### PR TITLE
README: Add info how to install yepkit-pykush module

### PR DESCRIPTION
**Pull request by mkasenberg**
The tested working version is yepkit-pykush-0.3.5.

### CODE REVIEW

**Comment by m-alperen-sener** [comment]
should we add this module to autoptsclient_requirements.txt? Even though It is not a hard dependency.

**Review by m-alperen-sener — APPROVED** [review]

**Review by m-alperen-sener — APPROVED** [review]

**Comment by MariuszSkamra** [comment]
Now, as the the is in the `*_requirements.txt` is it needed to mention about it in README? :)

**Comment by m-alperen-sener** [comment]
> Now, as the the is in the `*_requirements.txt` is it needed to mention about it in README? :)

Actually that sounds right.

**Review by MariuszSkamra — APPROVED** [review]

**Comment by MicImbriani** [comment]
Apologies for re-opening this discussion after so long. Why was this module added to the requirements at this specific moment? Has something changed that made it a hard dependency?

**Pull request merged**
