### PR TITLE
zephyr: Prefer EATT for GATT tests

### PR DESCRIPTION
**Pull request by sjanc**
Make PTS use EATT for running GATT tests.

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run zephyr GATT

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1008#issuecomment-1739147772 after 15:37:31.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GATT    GATT/CL/GPM/BV-11-C             FAIL<br>GATT    GATT/SR/GAR/BI-03-C             FAIL<br>GATT    GATT/SR/GAR/BI-04-C             FAIL<br>GATT    GATT/SR/GAR/BI-09-C             FAIL<br>GATT    GATT/SR/GAR/BI-10-C             FAIL<br>GATT    GATT/SR/GAR/BI-15-C             FAIL</details>
<details><summary>Successful tests</summary>GATT    GATT/CL/GAC/BV-01-C             PASS<br>GATT    GATT/CL/GAD/BV-01-C             PASS<br>GATT    GATT/CL/GAD/BV-02-C             PASS<br>GATT    GATT/CL/GAD/BV-03-C             PASS<br>GATT    GATT/CL/GAD/BV-04-C             PASS<br>GATT    GATT/CL/GAD/BV-05-C             PASS<br>GATT    GATT/CL/GAD/BV-06-C             PASS<br>GATT    GATT/CL/GAI/BI-01-C             PASS<br>GATT    GATT/CL/GAN/BV-02-C             PASS<br>GATT    GATT/CL/GAR/BI-01-C             PASS<br>GATT    GATT/CL/GAR/BI-02-C             PASS<br>GATT    GATT/CL/GAR/BI-03-C             PASS<br>GATT    GATT/CL/GAR/BI-04-C             PASS<br>GATT    GATT/CL/GAR/BI-05-C             PASS<br>GATT    GATT/CL/GAR/BI-06-C             PASS<br>GATT    GATT/CL/GAR/BI-07-C             PASS<br>GATT    GATT/CL/GAR/BI-09-C             PASS<br>GATT    GATT/CL/GAR/BI-10-C             PASS<br>GATT    GATT/CL/GAR/BI-11-C             PASS<br>GATT    GATT/CL/GAR/BI-12-C             PASS<br>GATT    GATT/CL/GAR/BI-13-C             PASS<br>GATT    GATT/CL/GAR/BI-14-C             PASS<br>GATT    GATT/CL/GAR/BI-15-C             PASS<br>GATT    GATT/CL/GAR/BI-16-C             PASS<br>GATT    GATT/CL/GAR/BI-17-C             PASS<br>GATT    GATT/CL/GAR/BI-18-C             PASS<br>GATT    GATT/CL/GAR/BI-19-C             PASS<br>GATT    GATT/CL/GAR/BI-20-C             PASS<br>GATT    GATT/CL/GAR/BI-21-C             PASS<br>GATT    GATT/CL/GAR/BI-22-C             PASS<br>GATT    GATT/CL/GAR/BI-35-C             PASS<br>GATT    GATT/CL/GAR/BI-36-C             PASS<br>GATT    GATT/CL/GAR/BI-38-C             PASS<br>GATT    GATT/CL/GAR/BI-40-C             PASS<br>GATT    GATT/CL/GAR/BI-42-C             PASS<br>GATT    GATT/CL/GAR/BI-44-C             PASS<br>GATT    GATT/CL/GAR/BV-01-C             PASS<br>GATT    GATT/CL/GAR/BV-03-C             PASS<br>GATT    GATT/CL/GAR/BV-04-C             PASS<br>GATT    GATT/CL/GAR/BV-05-C             PASS<br>GATT    GATT/CL/GAR/BV-06-C             PASS<br>GATT    GATT/CL/GAR/BV-07-C             PASS<br>GATT    GATT/CL/GAR/BV-08-C             PASS<br>GATT    GATT/CL/GAS/BV-01-C             PASS<br>GATT    GATT/CL/GAS/BV-02-C             PASS<br>GATT    GATT/CL/GAS/BV-04-C             PASS<br>GATT    GATT/CL/GAS/BV-05-C             PASS<br>GATT    GATT/CL/GAT/BV-01-C             PASS<br>GATT    GATT/CL/GAT/BV-02-C             PASS<br>GATT    GATT/CL/GAT/BV-03-C             PASS<br>GATT    GATT/CL/GAW/BI-02-C             PASS<br>GATT    GATT/CL/GAW/BI-03-C             PASS<br>GATT    GATT/CL/GAW/BI-04-C             PASS<br>GATT    GATT/CL/GAW/BI-05-C             PASS<br>GATT    GATT/CL/GAW/BI-06-C             PASS<br>GATT    GATT/CL/GAW/BI-07-C             PASS<br>GATT    GATT/CL/GAW/BI-09-C             PASS<br>GATT    GATT/CL/GAW/BI-33-C             PASS<br>GATT    GATT/CL/GAW/BI-34-C             PASS<br>GATT    GATT/CL/GAW/BV-01-C             PASS<br>GATT    GATT/CL/GAW/BV-03-C             PASS<br>GATT    GATT/CL/GAW/BV-05-C             PASS<br>GATT    GATT/CL/GAW/BV-08-C             PASS<br>GATT    GATT/SR/GAC/BI-01-C             PASS<br>GATT    GATT/SR/GAC/BV-01-C             PASS<br>GATT    GATT/SR/GAD/BV-01-C             PASS<br>GATT    GATT/SR/GAD/BV-02-C             PASS<br>GATT    GATT/SR/GAD/BV-03-C             PASS<br>GATT    GATT/SR/GAD/BV-04-C             PASS<br>GATT    GATT/SR/GAD/BV-05-C             PASS<br>GATT    GATT/SR/GAD/BV-06-C             PASS<br>GATT    GATT/SR/GAR/BI-01-C             PASS<br>GATT    GATT/SR/GAR/BI-02-C             PASS<br>GATT    GATT/SR/GAR/BI-05-C             PASS<br>GATT    GATT/SR/GAR/BI-06-C             PASS<br>GATT    GATT/SR/GAR/BI-07-C             PASS<br>GATT    GATT/SR/GAR/BI-08-C             PASS<br>GATT    GATT/SR/GAR/BI-11-C             PASS<br>GATT    GATT/SR/GAR/BI-12-C             PASS<br>GATT    GATT/SR/GAR/BI-13-C             PASS<br>GATT    GATT/SR/GAR/BI-14-C             PASS<br>GATT    GATT/SR/GAR/BV-01-C             PASS<br>GATT    GATT/SR/GAR/BV-03-C             PASS<br>GATT    GATT/SR/GAR/BV-04-C             PASS</details>

**Review by mkasenberg — APPROVED** [review]

**Comment by sjanc** [comment]
#AutoPTS run zephyr GATT

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1008#issuecomment-1746515257 after 11:46:37.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GATT    GATT/CL/GPM/BV-11-C             FAIL<br>GATT    GATT/SR/GAR/BI-03-C             FAIL<br>GATT    GATT/SR/GAR/BI-04-C             FAIL<br>GATT    GATT/SR/GAR/BI-09-C             FAIL<br>GATT    GATT/SR/GAR/BI-10-C             FAIL<br>GATT    GATT/SR/GAR/BI-15-C             FAIL</details>
<details><summary>Successful tests</summary>GATT    GATT/CL/GAC/BV-01-C             PASS<br>GATT    GATT/CL/GAD/BV-01-C             PASS<br>GATT    GATT/CL/GAD/BV-02-C             PASS<br>GATT    GATT/CL/GAD/BV-03-C             PASS<br>GATT    GATT/CL/GAD/BV-04-C             PASS<br>GATT    GATT/CL/GAD/BV-05-C             PASS<br>GATT    GATT/CL/GAD/BV-06-C             PASS<br>GATT    GATT/CL/GAI/BI-01-C             PASS<br>GATT    GATT/CL/GAN/BV-02-C             PASS<br>GATT    GATT/CL/GAR/BI-01-C             PASS<br>GATT    GATT/CL/GAR/BI-02-C             PASS<br>GATT    GATT/CL/GAR/BI-03-C             PASS<br>GATT    GATT/CL/GAR/BI-04-C             PASS<br>GATT    GATT/CL/GAR/BI-05-C             PASS<br>GATT    GATT/CL/GAR/BI-06-C             PASS<br>GATT    GATT/CL/GAR/BI-07-C             PASS<br>GATT    GATT/CL/GAR/BI-09-C             PASS<br>GATT    GATT/CL/GAR/BI-10-C             PASS<br>GATT    GATT/CL/GAR/BI-11-C             PASS<br>GATT    GATT/CL/GAR/BI-12-C             PASS<br>GATT    GATT/CL/GAR/BI-13-C             PASS<br>GATT    GATT/CL/GAR/BI-14-C             PASS<br>GATT    GATT/CL/GAR/BI-15-C             PASS<br>GATT    GATT/CL/GAR/BI-16-C             PASS<br>GATT    GATT/CL/GAR/BI-17-C             PASS<br>GATT    GATT/CL/GAR/BI-20-C             PASS<br>GATT    GATT/CL/GAR/BI-21-C             PASS<br>GATT    GATT/CL/GAR/BI-22-C             PASS<br>GATT    GATT/CL/GAR/BI-35-C             PASS<br>GATT    GATT/CL/GAR/BI-36-C             PASS<br>GATT    GATT/CL/GAR/BI-38-C             PASS<br>GATT    GATT/CL/GAR/BI-40-C             PASS<br>GATT    GATT/CL/GAR/BI-42-C             PASS<br>GATT    GATT/CL/GAR/BI-44-C             PASS<br>GATT    GATT/CL/GAR/BV-01-C             PASS<br>GATT    GATT/CL/GAR/BV-03-C             PASS<br>GATT    GATT/CL/GAR/BV-04-C             PASS<br>GATT    GATT/CL/GAR/BV-05-C             PASS<br>GATT    GATT/CL/GAR/BV-06-C             PASS<br>GATT    GATT/CL/GAR/BV-07-C             PASS<br>GATT    GATT/CL/GAR/BV-08-C             PASS<br>GATT    GATT/CL/GAS/BV-01-C             PASS<br>GATT    GATT/CL/GAS/BV-02-C             PASS<br>GATT    GATT/CL/GAS/BV-04-C             PASS<br>GATT    GATT/CL/GAS/BV-05-C             PASS<br>GATT    GATT/CL/GAT/BV-01-C             PASS<br>GATT    GATT/CL/GAT/BV-02-C             PASS<br>GATT    GATT/CL/GAT/BV-03-C             PASS<br>GATT    GATT/CL/GAW/BI-02-C             PASS<br>GATT    GATT/CL/GAW/BI-03-C             PASS<br>GATT    GATT/CL/GAW/BI-04-C             PASS<br>GATT    GATT/CL/GAW/BI-05-C             PASS<br>GATT    GATT/CL/GAW/BI-06-C             PASS<br>GATT    GATT/CL/GAW/BI-07-C             PASS<br>GATT    GATT/CL/GAW/BI-09-C             PASS<br>GATT    GATT/CL/GAW/BI-33-C             PASS<br>GATT    GATT/CL/GAW/BV-01-C             PASS<br>GATT    GATT/CL/GAW/BV-03-C             PASS<br>GATT    GATT/CL/GAW/BV-05-C             PASS<br>GATT    GATT/CL/GAW/BV-08-C             PASS<br>GATT    GATT/SR/GAC/BI-01-C             PASS<br>GATT    GATT/SR/GAC/BV-01-C             PASS<br>GATT    GATT/SR/GAD/BV-01-C             PASS<br>GATT    GATT/SR/GAD/BV-02-C             PASS<br>GATT    GATT/SR/GAD/BV-03-C             PASS<br>GATT    GATT/SR/GAD/BV-04-C             PASS<br>GATT    GATT/SR/GAD/BV-05-C             PASS<br>GATT    GATT/SR/GAD/BV-06-C             PASS<br>GATT    GATT/SR/GAR/BI-01-C             PASS<br>GATT    GATT/SR/GAR/BI-02-C             PASS<br>GATT    GATT/SR/GAR/BI-05-C             PASS<br>GATT    GATT/SR/GAR/BI-06-C             PASS<br>GATT    GATT/SR/GAR/BI-07-C             PASS<br>GATT    GATT/SR/GAR/BI-08-C             PASS<br>GATT    GATT/SR/GAR/BI-11-C             PASS<br>GATT    GATT/SR/GAR/BI-12-C             PASS<br>GATT    GATT/SR/GAR/BI-13-C             PASS<br>GATT    GATT/SR/GAR/BI-14-C             PASS<br>GATT    GATT/SR/GAR/BV-01-C             PASS<br>GATT    GATT/SR/GAR/BV-03-C             PASS<br>GATT    GATT/SR/GAR/BV-04-C             PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run zephyr GATT

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1008#issuecomment-1750061284 after 08:40:23.

**Comment by sjanc** [comment]
#AutoPTS run zephyr  GATT/CL/GAI/BV-01-C  GATT/CL/GAN/BV-01-C GATT/CL/GAR/BI-18-C GATT/CL/GAR/BI-19-C GATT/CL/GAR/BV-10-C GATT/CL/GAR/BV-11-C GATT/CL/GAW/BI-11-C GATT/CL/GAW/BI-12-C GATT/CL/GAW/BI-13-C GATT/CL/GAW/BV-02-C GATT/CL/GAW/BV-05-C GATT/CL/GAW/BV-09-C GATT/CL/GPM/BV-11-C  GATT/SR/GAR/BI-03-C  GATT/SR/GAR/BI-04-C  GATT/SR/GAR/BI-09-C  GATT/SR/GAR/BI-10-C  GATT/SR/GAR/BI-15-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1008#issuecomment-1766007444 after 11:17:49.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GATT    GATT/CL/GAI/BV-01-C             FATAL ERROR<br>GATT    GATT/CL/GAN/BV-01-C             FATAL ERROR<br>GATT    GATT/CL/GAR/BV-10-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/CL/GAR/BV-11-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/CL/GAW/BI-11-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/CL/GAW/BI-12-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/CL/GAW/BI-13-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/CL/GAW/BV-02-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/CL/GAW/BV-09-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/CL/GPM/BV-11-C             FAIL<br>GATT    GATT/SR/GAR/BI-03-C             FAIL<br>GATT    GATT/SR/GAR/BI-04-C             FAIL<br>GATT    GATT/SR/GAR/BI-09-C             FAIL<br>GATT    GATT/SR/GAR/BI-10-C             FAIL<br>GATT    GATT/SR/GAR/BI-15-C             FAIL</details>
<details><summary>Successful tests</summary>GATT    GATT/CL/GAR/BI-18-C             PASS<br>GATT    GATT/CL/GAR/BI-19-C             PASS<br>GATT    GATT/CL/GAW/BV-05-C             PASS</details>

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1008#issuecomment-1824130680 after 11:25:50.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GATT    GATT/CL/GAR/BV-10-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/CL/GAR/BV-11-C             UNKNOWN VERDICT: Timeout. Adjust TSPX_time_guard value if user need more time.<br>GATT    GATT/SR/GAC/BV-01-C             FAIL<br>GATT    GATT/SR/GAR/BV-06-C             FATAL ERROR</details>
<details><summary>Successful tests</summary>GATT    GATT/CL/GAC/BV-01-C             PASS<br>GATT    GATT/CL/GAD/BV-01-C             PASS<br>GATT    GATT/CL/GAD/BV-02-C             PASS<br>GATT    GATT/CL/GAD/BV-03-C             PASS<br>GATT    GATT/CL/GAD/BV-04-C             PASS<br>GATT    GATT/CL/GAD/BV-05-C             PASS<br>GATT    GATT/CL/GAD/BV-06-C             PASS<br>GATT    GATT/CL/GAI/BI-01-C             PASS<br>GATT    GATT/CL/GAI/BV-01-C             PASS<br>GATT    GATT/CL/GAN/BV-01-C             PASS<br>GATT    GATT/CL/GAN/BV-02-C             PASS<br>GATT    GATT/CL/GAR/BI-01-C             PASS<br>GATT    GATT/CL/GAR/BI-02-C             PASS<br>GATT    GATT/CL/GAR/BI-03-C             PASS<br>GATT    GATT/CL/GAR/BI-04-C             PASS<br>GATT    GATT/CL/GAR/BI-05-C             PASS<br>GATT    GATT/CL/GAR/BI-06-C             PASS<br>GATT    GATT/CL/GAR/BI-07-C             PASS<br>GATT    GATT/CL/GAR/BI-09-C             PASS<br>GATT    GATT/CL/GAR/BI-10-C             PASS<br>GATT    GATT/CL/GAR/BI-11-C             PASS<br>GATT    GATT/CL/GAR/BI-12-C             PASS<br>GATT    GATT/CL/GAR/BI-13-C             PASS<br>GATT    GATT/CL/GAR/BI-14-C             PASS<br>GATT    GATT/CL/GAR/BI-15-C             PASS<br>GATT    GATT/CL/GAR/BI-16-C             PASS<br>GATT    GATT/CL/GAR/BI-17-C             PASS<br>GATT    GATT/CL/GAR/BI-18-C             PASS<br>GATT    GATT/CL/GAR/BI-19-C             PASS<br>GATT    GATT/CL/GAR/BI-20-C             PASS<br>GATT    GATT/CL/GAR/BI-21-C             PASS<br>GATT    GATT/CL/GAR/BI-22-C             PASS<br>GATT    GATT/CL/GAR/BI-35-C             PASS<br>GATT    GATT/CL/GAR/BI-36-C             PASS<br>GATT    GATT/CL/GAR/BI-38-C             PASS<br>GATT    GATT/CL/GAR/BI-40-C             PASS<br>GATT    GATT/CL/GAR/BI-42-C             PASS<br>GATT    GATT/CL/GAR/BI-44-C             PASS<br>GATT    GATT/CL/GAR/BV-01-C             PASS<br>GATT    GATT/CL/GAR/BV-03-C             PASS<br>GATT    GATT/CL/GAR/BV-04-C             PASS<br>GATT    GATT/CL/GAR/BV-05-C             PASS<br>GATT    GATT/CL/GAR/BV-06-C             PASS<br>GATT    GATT/CL/GAR/BV-07-C             PASS<br>GATT    GATT/CL/GAR/BV-08-C             PASS<br>GATT    GATT/CL/GAS/BV-01-C             PASS<br>GATT    GATT/CL/GAS/BV-02-C             PASS<br>GATT    GATT/CL/GAS/BV-04-C             PASS<br>GATT    GATT/CL/GAS/BV-05-C             PASS<br>GATT    GATT/CL/GAT/BV-01-C             PASS<br>GATT    GATT/CL/GAT/BV-02-C             PASS<br>GATT    GATT/CL/GAT/BV-03-C             PASS<br>GATT    GATT/CL/GAW/BI-02-C             PASS<br>GATT    GATT/CL/GAW/BI-03-C             PASS<br>GATT    GATT/CL/GAW/BI-04-C             PASS<br>GATT    GATT/CL/GAW/BI-05-C             PASS<br>GATT    GATT/CL/GAW/BI-06-C             PASS<br>GATT    GATT/CL/GAW/BI-07-C             PASS<br>GATT    GATT/CL/GAW/BI-08-C             PASS<br>GATT    GATT/CL/GAW/BI-09-C             PASS<br>GATT    GATT/CL/GAW/BI-11-C             PASS<br>GATT    GATT/CL/GAW/BI-12-C             PASS<br>GATT    GATT/CL/GAW/BI-13-C             PASS<br>GATT    GATT/CL/GAW/BI-33-C             PASS<br>GATT    GATT/CL/GAW/BI-34-C             PASS (2)<br>GATT    GATT/CL/GAW/BV-01-C             PASS<br>GATT    GATT/CL/GAW/BV-02-C             PASS<br>GATT    GATT/CL/GAW/BV-03-C             PASS<br>GATT    GATT/CL/GAW/BV-05-C             PASS<br>GATT    GATT/CL/GAW/BV-08-C             PASS<br>GATT    GATT/CL/GAW/BV-09-C             PASS<br>GATT    GATT/SR/GAC/BI-01-C             PASS<br>GATT    GATT/SR/GAD/BV-01-C             PASS<br>GATT    GATT/SR/GAD/BV-02-C             PASS<br>GATT    GATT/SR/GAD/BV-03-C             PASS<br>GATT    GATT/SR/GAD/BV-04-C             PASS<br>GATT    GATT/SR/GAD/BV-05-C             PASS<br>GATT    GATT/SR/GAD/BV-06-C             PASS<br>GATT    GATT/SR/GAI/BV-01-C             PASS<br>GATT    GATT/SR/GAN/BV-01-C             PASS<br>GATT    GATT/SR/GAN/BV-02-C             PASS<br>GATT    GATT/SR/GAR/BI-01-C             PASS<br>GATT    GATT/SR/GAR/BI-02-C             PASS<br>GATT    GATT/SR/GAR/BI-03-C             PASS<br>GATT    GATT/SR/GAR/BI-04-C             PASS<br>GATT    GATT/SR/GAR/BI-05-C             PASS<br>GATT    GATT/SR/GAR/BI-06-C             PASS<br>GATT    GATT/SR/GAR/BI-07-C             PASS<br>GATT    GATT/SR/GAR/BI-08-C             PASS<br>GATT    GATT/SR/GAR/BI-09-C             PASS<br>GATT    GATT/SR/GAR/BI-10-C             PASS<br>GATT    GATT/SR/GAR/BI-11-C             PASS<br>GATT    GATT/SR/GAR/BI-12-C             PASS<br>GATT    GATT/SR/GAR/BI-13-C             PASS<br>GATT    GATT/SR/GAR/BI-14-C             PASS<br>GATT    GATT/SR/GAR/BI-15-C             PASS<br>GATT    GATT/SR/GAR/BI-16-C             PASS<br>GATT    GATT/SR/GAR/BI-17-C             PASS<br>GATT    GATT/SR/GAR/BI-18-C             PASS<br>GATT    GATT/SR/GAR/BI-19-C             PASS<br>GATT    GATT/SR/GAR/BI-20-C             PASS<br>GATT    GATT/SR/GAR/BI-21-C             PASS<br>GATT    GATT/SR/GAR/BI-22-C             PASS<br>GATT    GATT/SR/GAR/BI-36-C             PASS<br>GATT    GATT/SR/GAR/BI-38-C             PASS<br>GATT    GATT/SR/GAR/BI-40-C             PASS<br>GATT    GATT/SR/GAR/BI-42-C             PASS<br>GATT    GATT/SR/GAR/BI-44-C             PASS<br>GATT    GATT/SR/GAR/BI-45-C             PASS<br>GATT    GATT/SR/GAR/BV-01-C             PASS<br>GATT    GATT/SR/GAR/BV-03-C             PASS<br>GATT    GATT/SR/GAR/BV-04-C             PASS<br>GATT    GATT/SR/GAR/BV-05-C             PASS<br>GATT    GATT/SR/GAR/BV-07-C             PASS<br>GATT    GATT/SR/GAR/BV-08-C             PASS<br>GATT    GATT/SR/GAR/BV-09-C             PASS<br>GATT    GATT/SR/GAR/BV-11-C             PASS<br>GATT    GATT/SR/GAR/BV-12-C             PASS<br>GATT    GATT/SR/GAS/BV-01-C             PASS<br>GATT    GATT/SR/GAS/BV-02-C             PASS<br>GATT    GATT/SR/GAS/BV-03-C             PASS<br>GATT    GATT/SR/GAS/BV-04-C             PASS<br>GATT    GATT/SR/GAS/BV-05-C             PASS<br>GATT    GATT/SR/GAS/BV-06-C             PASS<br>GATT    GATT/SR/GAS/BV-07-C             PASS<br>GATT    GATT/SR/GAS/BV-08-C             PASS<br>GATT    GATT/SR/GAT/BV-01-C             PASS<br>GATT    GATT/SR/GAW/BI-01-C             PASS<br>GATT    GATT/SR/GAW/BI-02-C             PASS<br>GATT    GATT/SR/GAW/BI-03-C             PASS<br>GATT    GATT/SR/GAW/BI-04-C             PASS<br>GATT    GATT/SR/GAW/BI-05-C             PASS<br>GATT    GATT/SR/GAW/BI-06-C             PASS<br>GATT    GATT/SR/GAW/BI-07-C             PASS<br>GATT    GATT/SR/GAW/BI-08-C             PASS<br>GATT    GATT/SR/GAW/BI-09-C             PASS<br>GATT    GATT/SR/GAW/BI-11-C             PASS<br>GATT    GATT/SR/GAW/BI-12-C             PASS<br>GATT    GATT/SR/GAW/BI-13-C             PASS<br>GATT    GATT/SR/GAW/BI-32-C             PASS<br>GATT    GATT/SR/GAW/BI-33-C             PASS<br>GATT    GATT/SR/GAW/BI-38-C             PASS<br>GATT    GATT/SR/GAW/BV-01-C             PASS<br>GATT    GATT/SR/GAW/BV-02-C             PASS<br>GATT    GATT/SR/GAW/BV-03-C             PASS<br>GATT    GATT/SR/GAW/BV-05-C             PASS<br>GATT    GATT/SR/GAW/BV-06-C             PASS<br>GATT    GATT/SR/GAW/BV-07-C             PASS<br>GATT    GATT/SR/GAW/BV-08-C             PASS<br>GATT    GATT/SR/GAW/BV-09-C             PASS<br>GATT    GATT/SR/GAW/BV-10-C             PASS<br>GATT    GATT/SR/GAW/BV-11-C             PASS<br>GATT    GATT/SR/GAW/BV-12-C             PASS<br>GATT    GATT/SR/GAW/BV-13-C             PASS<br>GATT    GATT/SR/GAW/BV-14-C             PASS<br>GATT    GATT/SR/GPM/BV-05-C             PASS<br>GATT    GATT/SR/UNS/BI-01-C             PASS<br>GATT    GATT/SR/UNS/BI-02-C             PASS</details>

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1008#issuecomment-1824438675 after 14:30:17.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GATT    GATT/SR/GAR/BV-06-C             PASS</details>

**Pull request merged**
