### PR TITLE
tools: cron: improve test case limit parameter

### PR DESCRIPTION
**Pull request by piotrnarajowski**
This will enable to run specified amount of test cases from among prefixes (when there is more than one) that are used with magic tag.

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT --test_case_limit 2

**Comment by piotrnarajowski** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2257861360, board: nrf52, estimated start time: 11:11:34

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT --test_case_limit 2

**Comment by piotrnarajowski** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2257877162, board: nrf52, estimated start time: 11:18:52, test case count: 2, estimated duration: None<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT --test_case_limit 3

**Comment by piotrnarajowski** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2257973049, board: nrf52, estimated start time: 12:08:15, test case count: 3, estimated duration: None<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2257973049, board: nrf52, estimated start time: 12:08:15, test case count: 3, estimated duration: 0:01:02<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT --test_case_limit 10

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2258107102, board: nrf52, estimated start time: 13:21:01, test case count: 10, estimated duration: 0:05:16<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C<br>GAP/BROB/BCST/BV-04-C<br>GAP/BROB/OBSV/BV-01-C<br>GAP/BROB/OBSV/BV-02-C<br>GAP/BROB/OBSV/BV-05-C<br>GAP/BROB/OBSV/BV-06-C<br>GAP/DISC/NONM/BV-01-C<br>GAP/DISC/NONM/BV-02-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT --test_case_limit 5

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2258277196, board: nrf52, estimated start time: 14:53:51, test case count: 5, estimated duration: 0:03:09<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C<br>GAP/BROB/BCST/BV-04-C<br>GAP/BROB/OBSV/BV-01-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2259980803, board: nrf52, estimated start time: 10:45:31, test case count: 3, estimated duration: 0:01:02<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by piotrnarajowski** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260182824, board: nrf52, estimated start time: 12:25:12

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260182824, board: nrf52, estimated start time: 12:25:52, test case count: 3, estimated duration: 0:01:02<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by piotrnarajowski** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260196361, board: nrf52, estimated start time: 12:33:13

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260196361, board: nrf52, estimated start time: 12:33:26, test case count: 3, estimated duration: 0:01:02<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260211643, board: nrf52, estimated start time: 12:40:58, test case count: 3, estimated duration: 0:01:02<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by piotrnarajowski** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260211643, board: nrf52, estimated start time: 12:45:56, test case count: 12, estimated duration: None<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C<br>GATT/CL/GAC/BV-01-C<br>GATT/CL/GAD/BV-01-C<br>GATT/CL/GAD/BV-02-C<br>L2CAP/COS/CFC/BV-01-C<br>L2CAP/COS/CFC/BV-02-C<br>L2CAP/COS/CFC/BV-03-C<br>DIS/SR/SGGIT/SER/BV-01-C<br>DIS/SR/SGGIT/CHA/BV-01-C<br>DIS/SR/SGGIT/CHA/BV-02-C</details>

**Comment by piotrnarajowski** [comment]
Job failed at setup

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260246161, board: nrf52, estimated start time: 13:01:04, test case count: 3, estimated duration: 0:01:02<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS</details>

**Comment by mkasenberg** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260280498, board: nrf52, estimated start time: 13:21:09, test case count: 3, estimated duration: 0:01:02<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by mkasenberg** [comment]
#AutoPTS run mynewt GAP GATT L2CAP DIS --test_case_limit 3

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260280498, board: nrf52, estimated start time: 13:42:26, test case count: 1, estimated duration: 0:00:18<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C</details>

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260318624, board: nrf52, estimated start time: 13:48:55, test case count: 3, estimated duration: 0:01:02<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C</details>

**Comment by codecoup-tester** [comment]
Job triggered with https://github.com/auto-pts/auto-pts/pull/1211#issuecomment-2260280498 has been canceled

**Review by mkasenberg — APPROVED** [review]

**Pull request merged**
