### PR TITLE
zephyr: Update workspace to PTS 8.5.1 and TCRL 2023-1

### PR DESCRIPTION
**Pull request by sjanc**
This also removes test plan xlsx as it isn't really usefull since user have to import project to Launch Studio anyway and can generate test plan from there.

### CODE REVIEW

**Comment by sjanc** [comment]
@mkasenberg FYI

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr VOCS VCS AICS IAS PACS ASCS BAP HAS CSIS MICP MICS VCP MCP

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1042#issuecomment-1810871620 after 19:19:34.

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Reason unknown

**Comment by sjanc** [comment]
#AutoPTS run zephyr VOCS VCS AICS IAS PACS ASCS BAP HAS CSIS MICP MICS VCP MCP

**Review by mkasenberg — APPROVED** [review]

**Pull request merged**
