### PR TITLE
mesh: fix rpr link 13 lt2 usage

### PR DESCRIPTION
**Pull request by alxelax**
MESH/SR/RPR/LNK/BV-13-C was implemented initially wrong in PTS. Test should use both LT and LT2.
PTS patch has been provided and will be available in the next PTS release.

### CODE REVIEW

**Comment by alxelax** [comment]
Related PTS ticket: https://support.bluetooth.com/hc/en-us/requests/28486

**Comment by sjanc** [comment]
can it be merged now or should we wait for next PTS release?

**Comment by alxelax** [comment]
It is better to merge now, then test will pass with the patch that can be found on the provided link with current PTS. 
The change will not break Mesh 1.0.1 CI compatibility anycase.
FYI @m-alperen-sener

**Comment by sjanc** [comment]
BTW PTS support request are private ;-)

**Review by sjanc — APPROVED** [review]

**Pull request merged**
