### PR TITLE
Add CAP Broadcast Assistant tests

### PR DESCRIPTION
**Pull request by mringwal**
I've added these tests for our stack. The ptsproject/cap.py is currently here:
https://github.com/bluekitchen/auto-pts/blob/develop-le-audio-broadcast/autopts/ptsprojects/btstack/cap.py

### CODE REVIEW

**Comment by mringwal** [comment]
Is the error related to the code in my PR?

**Comment by mkasenberg** [comment]
> Is the error related to the code in my PR?

This github action was supposed to trigger some AutoPTS tests on our local machine if PR patch changes a wid handler

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr nrf53 CAP

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/auto-pts/auto-pts/pull/1170#issuecomment-2124382210, estimated start time: 11:59:16, test case count: 68, estimated duration: 0:34:21<details><summary>Test cases to be run</summary>CAP/INI/UST/BV-01-C<br>CAP/INI/UST/BV-02-C<br>CAP/INI/UST/BV-03-C<br>CAP/INI/UST/BV-04-C<br>CAP/INI/UST/BV-05-C<br>CAP/INI/UST/BV-06-C<br>CAP/INI/UST/BV-07-C<br>CAP/INI/UST/BV-08-C<br>CAP/INI/UST/BV-09-C<br>CAP/INI/UST/BV-10-C<br>CAP/INI/UST/BV-11-C<br>CAP/INI/UST/BV-12-C<br>CAP/INI/UST/BV-13-C<br>CAP/INI/UST/BV-14-C<br>CAP/INI/UST/BV-15-C<br>CAP/INI/UST/BV-16-C<br>CAP/INI/UST/BV-17-C<br>CAP/INI/UST/BV-18-C<br>CAP/INI/UST/BV-19-C<br>CAP/INI/UST/BV-20-C<br>CAP/INI/UST/BV-21-C<br>CAP/INI/UST/BV-22-C<br>CAP/INI/UST/BV-23-C<br>CAP/INI/UST/BV-24-C<br>CAP/INI/UST/BV-25-C<br>CAP/INI/UST/BV-26-C<br>CAP/INI/UST/BV-27-C<br>CAP/INI/UST/BV-28-C<br>CAP/INI/UST/BV-29-C<br>CAP/INI/UST/BV-30-C<br>CAP/INI/UST/BV-31-C<br>CAP/INI/UST/BV-32-C<br>CAP/INI/UST/BV-33-C<br>CAP/INI/UST/BV-34-C<br>CAP/INI/UST/BV-35-C<br>CAP/INI/UST/BV-36-C<br>CAP/INI/UST/BV-37-C<br>CAP/INI/UST/BV-40-C<br>CAP/INI/UST/BV-41-C<br>CAP/INI/UST/BV-42-C<br>CAP/INI/BST/BV-01-C<br>CAP/INI/BST/BV-02-C<br>CAP/INI/BST/BV-03-C<br>CAP/INI/BST/BV-04-C<br>CAP/INI/BST/BV-05-C<br>CAP/INI/BST/BV-06-C<br>CAP/INI/BST/BV-07-C<br>CAP/INI/BST/BV-08-C<br>CAP/INI/BST/BV-09-C<br>CAP/INI/BST/BV-10-C<br>CAP/INI/BST/BV-11-C<br>CAP/INI/BST/BV-12-C<br>CAP/INI/BST/BV-13-C<br>CAP/INI/BST/BV-14-C<br>CAP/INI/BST/BV-15-C<br>CAP/INI/BST/BV-16-C<br>CAP/INI/BST/BV-17-C<br>CAP/INI/ERR/BI-01-C<br>CAP/ACC/ADV/BV-01-C<br>CAP/ACC/ERR/BI-01-C<br>CAP/ACC/ERR/BI-02-C<br>CAP/ACC/ERR/BI-03-C<br>CAP/ACC/ERR/BI-04-C<br>CAP/CL/ADV/BV-01-C<br>CAP/CL/ADV/BV-02-C<br>CAP/CL/ADV/BV-03-C<br>CAP/CL/CGGIT/SER/BV-01-C<br>CAP/CL/CGGIT/SER/BV-02-C</details>

**Comment by codecoup-tester** [comment]
Job failed at setup

**Comment by codecoup-tester** [comment]
Scheduled PR, https://github.com/auto-pts/auto-pts/pull/1170#issuecomment-2124382210, estimated start time: 12:17:35, test case count: 68, estimated duration: 0:34:21<details><summary>Test cases to be run</summary>CAP/INI/UST/BV-01-C<br>CAP/INI/UST/BV-02-C<br>CAP/INI/UST/BV-03-C<br>CAP/INI/UST/BV-04-C<br>CAP/INI/UST/BV-05-C<br>CAP/INI/UST/BV-06-C<br>CAP/INI/UST/BV-07-C<br>CAP/INI/UST/BV-08-C<br>CAP/INI/UST/BV-09-C<br>CAP/INI/UST/BV-10-C<br>CAP/INI/UST/BV-11-C<br>CAP/INI/UST/BV-12-C<br>CAP/INI/UST/BV-13-C<br>CAP/INI/UST/BV-14-C<br>CAP/INI/UST/BV-15-C<br>CAP/INI/UST/BV-16-C<br>CAP/INI/UST/BV-17-C<br>CAP/INI/UST/BV-18-C<br>CAP/INI/UST/BV-19-C<br>CAP/INI/UST/BV-20-C<br>CAP/INI/UST/BV-21-C<br>CAP/INI/UST/BV-22-C<br>CAP/INI/UST/BV-23-C<br>CAP/INI/UST/BV-24-C<br>CAP/INI/UST/BV-25-C<br>CAP/INI/UST/BV-26-C<br>CAP/INI/UST/BV-27-C<br>CAP/INI/UST/BV-28-C<br>CAP/INI/UST/BV-29-C<br>CAP/INI/UST/BV-30-C<br>CAP/INI/UST/BV-31-C<br>CAP/INI/UST/BV-32-C<br>CAP/INI/UST/BV-33-C<br>CAP/INI/UST/BV-34-C<br>CAP/INI/UST/BV-35-C<br>CAP/INI/UST/BV-36-C<br>CAP/INI/UST/BV-37-C<br>CAP/INI/UST/BV-40-C<br>CAP/INI/UST/BV-41-C<br>CAP/INI/UST/BV-42-C<br>CAP/INI/BST/BV-01-C<br>CAP/INI/BST/BV-02-C<br>CAP/INI/BST/BV-03-C<br>CAP/INI/BST/BV-04-C<br>CAP/INI/BST/BV-05-C<br>CAP/INI/BST/BV-06-C<br>CAP/INI/BST/BV-07-C<br>CAP/INI/BST/BV-08-C<br>CAP/INI/BST/BV-09-C<br>CAP/INI/BST/BV-10-C<br>CAP/INI/BST/BV-11-C<br>CAP/INI/BST/BV-12-C<br>CAP/INI/BST/BV-13-C<br>CAP/INI/BST/BV-14-C<br>CAP/INI/BST/BV-15-C<br>CAP/INI/BST/BV-16-C<br>CAP/INI/BST/BV-17-C<br>CAP/INI/ERR/BI-01-C<br>CAP/ACC/ADV/BV-01-C<br>CAP/ACC/ERR/BI-01-C<br>CAP/ACC/ERR/BI-02-C<br>CAP/ACC/ERR/BI-03-C<br>CAP/ACC/ERR/BI-04-C<br>CAP/CL/ADV/BV-01-C<br>CAP/CL/ADV/BV-02-C<br>CAP/CL/ADV/BV-03-C<br>CAP/CL/CGGIT/SER/BV-01-C<br>CAP/CL/CGGIT/SER/BV-02-C</details>

**Review by mkasenberg — APPROVED** [review]

**Comment by mringwal** [comment]
Great, thanks!

**Pull request merged**
