### PR TITLE
bot: common: Add report txt without tag to githubdrive

### PR DESCRIPTION
**Pull request by mkasenberg**
A datetime tag in report txt file name prevents diff view in GitHub, but it is still sometimes useful. To compromise, just add a second same report file, but without a tag.

### CODE REVIEW

**Review by MariuszSkamra — APPROVED** [review]

**Comment by mkasenberg** [comment]
#AutoPTS run mynewt GAP/ADV/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/991#issuecomment-1699251519 after 16:15:16.

**Comment by mkasenberg** [comment]
#AutoPTS run zephyr GAP/ADV/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/991#issuecomment-1699320569 after 16:45:39.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/ADV/BV-01-C                 PASS</details>

**Pull request merged**
