### PR TITLE
Mynewt: fixes for GAP/SEC/SEM

### PR DESCRIPTION
**Pull request by KKopyscinski**
Added tests to respective overlays.
Accomodated some wids to use GATT Client service, when enabled. Added setting in GAP stack to set if User Interaction is available in pairing.

### CODE REVIEW

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/945#issuecomment-1592998675 after 15:00:48.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/945#issuecomment-1592998675 after 15:12:03.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/945#issuecomment-1592998675 after 16:05:06.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/945#issuecomment-1592998675 after 08:19:45.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/945#issuecomment-1592998675 after 14:46:24.

**Comment by mkasenberg** [comment]
#AutoPTS run mynewt GAP/SEC/AUT

**Review by sjanc — APPROVED** [review]

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/945#issuecomment-1594708954 after 15:53:14.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GAP     GAP/SEC/AUT/BV-25-C             INCONC</details>
<details><summary>Successful tests</summary>GAP     GAP/SEC/AUT/BV-11-C             PASS<br>GAP     GAP/SEC/AUT/BV-12-C             PASS<br>GAP     GAP/SEC/AUT/BV-13-C             PASS<br>GAP     GAP/SEC/AUT/BV-14-C             PASS<br>GAP     GAP/SEC/AUT/BV-17-C             PASS<br>GAP     GAP/SEC/AUT/BV-18-C             PASS<br>GAP     GAP/SEC/AUT/BV-19-C             PASS<br>GAP     GAP/SEC/AUT/BV-20-C             PASS<br>GAP     GAP/SEC/AUT/BV-21-C             PASS<br>GAP     GAP/SEC/AUT/BV-22-C             PASS<br>GAP     GAP/SEC/AUT/BV-23-C             PASS<br>GAP     GAP/SEC/AUT/BV-24-C             PASS<br>GAP     GAP/SEC/AUT/BV-27-C             PASS</details>

**Pull request merged**
