### PR TITLE
zephyr: micp: fix MICP wid

### PR DESCRIPTION
**Pull request by piotrnarajowski**
Fix characteristic UUID from MMI that changed after PTS update. Fixes MICP/CL/CGGIT/CHA/BV-01-C

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
#AutoPTS run zephyr MICP

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1139#issuecomment-2019920986 after 10:28:02.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>MICP    MICP/CL/CGGIT/CHA/BV-01-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-02-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-03-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-04-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-05-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-06-C       PASS<br>MICP    MICP/CL/CGGIT/CHA/BV-07-C       PASS<br>MICP    MICP/CL/CGGIT/SER/BV-01-C       PASS<br>MICP    MICP/CL/CGGIT/SER/BV-02-C       PASS<br>MICP    MICP/CL/CP/BV-01-C              PASS<br>MICP    MICP/CL/CP/BV-02-C              PASS<br>MICP    MICP/CL/CP/BV-03-C              PASS<br>MICP    MICP/CL/CP/BV-04-C              PASS<br>MICP    MICP/CL/CP/BV-05-C              PASS<br>MICP    MICP/CL/SPE/BI-01-C             PASS<br>MICP    MICP/CL/SPE/BI-02-C             PASS<br>MICP    MICP/CL/SPE/BI-03-C             PASS<br>MICP    MICP/CL/SPE/BI-04-C             PASS<br>MICP    MICP/CL/SPE/BI-05-C             PASS<br>MICP    MICP/CL/SPE/BI-06-C             PASS<br>MICP    MICP/CL/SPE/BI-07-C             PASS<br>MICP    MICP/CL/SPE/BI-08-C             PASS<br>MICP    MICP/CL/SPE/BI-09-C             PASS<br>MICP    MICP/CL/SPE/BI-10-C             PASS<br>MICP    MICP/CL/SPE/BI-11-C             PASS<br>MICP    MICP/CL/SPE/BI-12-C             PASS</details>

**Comment by piotrnarajowski** [comment]
@KKopyscinski please review

**Review by sjanc — APPROVED** [review]

**Pull request merged**
