### PR TITLE
mynewt: fixes for EATT tests

### PR DESCRIPTION
**Pull request by KKopyscinski**
Adds support for Read Multiple Variable length in GATT Client service. Adds missing WIDs

### CODE REVIEW

**Comment by KKopyscinski** [comment]
This requires Mynewt with implemented EATT and modified workspace

**Comment by mkasenberg** [comment]
#AutoPTS run mynewt GATT/CL/GAR/BV-08-C GATT/CL/GAR/BV-10-C GATT/CL/GAR/BI-36-C GATT/CL/GAR/BI-38-C GATT/CL/GAR/BI-42-C GATT/CL/GAR/BI-44-C GATT/CL/GAN/BV-02-C GATT/CL/GAT/BV-03-C GATT/SR/GAC/BI-01-C GATT/SR/GAR/BV-09-C GATT/SR/GAR/BV-11-C GATT/SR/GAR/BI-36-C GATT/SR/GAR/BI-38-C GATT/SR/GAR/BI-42-C GATT/SR/GAR/BI-44-C GATT/SR/GAN/BV-02-C GATT/SR/GPM/BV-05-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/978#issuecomment-1754934492 after 12:31:25.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/978#issuecomment-1754934492 after 12:44:27.

**Review by sjanc — APPROVED** [review]

**Pull request merged**
