### PR TITLE
mynewt: bot: add progresses to mail report

### PR DESCRIPTION
**Pull request by piotrnarajowski**
This patch adds progresses to mynewt email report.

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt AICS --test_case_limit 1

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP --test_case_limit 1

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/auto-pts/auto-pts/pull/1192#issuecomment-2182485503, board: nrf52, estimated start time: 12:33:49, test case count: 1, estimated duration: 0:00:18<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/BROB/BCST/BV-01-C           PASS</details>

**Review by mkasenberg — APPROVED** [review]

**Pull request merged**
