### PR TITLE
zephyr: tester: Fix HAP wid handlers

### PR DESCRIPTION
**Pull request by piotrnarajowski**
Fix wid that handles connection to PTS, add missing wid handlers, fix hauc discovery data parsing
Fixes HAP/HAUC/DISC/BV-01-C, HAP/HAUC/SGGIT/SER/BV-01-C, HAP/IAC/CGGIT/CHA/BV-01-C

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
#AutoPTS run zephyr HAP

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/auto-pts/auto-pts/pull/1137#issuecomment-2015342438 after 16:30:37.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>HAP     HAP/HA/DISC/BV-04-C             FATAL ERROR<br>HAP     HAP/HAUC/STR/BV-01-C            BTP ERROR</details>
<details><summary>Successful tests</summary>HAP     HAP/HA/DISC/BV-01-C             PASS<br>HAP     HAP/HA/DISC/BV-02-C             PASS<br>HAP     HAP/HA/DISC/BV-03-C             PASS<br>HAP     HAP/HA/DISC/BV-05-C             PASS<br>HAP     HAP/HA/DISC/BV-06-C             PASS<br>HAP     HAP/HA/SGGIT/SER/BV-01-C        PASS<br>HAP     HAP/HA/SGGIT/SER/BV-02-C        PASS<br>HAP     HAP/HA/SGGIT/SER/BV-03-C        PASS<br>HAP     HAP/HA/SGGIT/SER/BV-04-C        PASS<br>HAP     HAP/HA/SGGIT/SER/BV-05-C        PASS<br>HAP     HAP/HA/SGGIT/SER/BV-06-C        PASS<br>HAP     HAP/HA/STR/BV-01-C              PASS<br>HAP     HAP/HA/STR/BV-02-C              PASS<br>HAP     HAP/HAUC/DISC/BV-01-C           PASS<br>HAP     HAP/HAUC/SGGIT/SER/BV-01-C      PASS<br>HAP     HAP/IAC/CGGIT/CHA/BV-01-C       PASS</details>

**Comment by piotrnarajowski** [comment]
@sjanc please review

**Review by sjanc — APPROVED** [review]

**Pull request merged**
